# Generated by Django 3.1.5 on 2021-01-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestackApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
