# Generated by Django 3.1.5 on 2021-01-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestackApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'demo1'), (2, 'demo2')], default=None),
        ),
    ]
