# Generated by Django 3.1.5 on 2021-01-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestackApp', '0005_confroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='currentStatus',
            field=models.CharField(choices=[('AV', 'Engg Manager'), ('BO', 'Office Manager')], default='AV', max_length=2),
        ),
    ]
