# Generated by Django 3.1.5 on 2021-01-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestackApp', '0006_auto_20210107_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='confroom',
            name='sitting',
            field=models.CharField(default='ram', max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(default='rere', max_length=18, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='rerrrr', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
    ]
